name: PyInstaller Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install pyinstaller -e ".[dev]"
      - name: Build executable
        run: pyinstaller --onefile -n monitor -m hetzner_ws_monitor.main
      - uses: actions/upload-artifact@v4
        with:
          name: monitor-${{ matrix.os }}
          path: dist/*
